name: "Test dev container features"
on:
  push:
    branches:
      - '**'
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features:
          - perl
        baseImage:
          - debian:latest
          - ubuntu:latest
          - mcr.microsoft.com/devcontainers/base:ubuntu
          - mcr.microsoft.com/devcontainers/base:alpine
    steps:
      - uses: actions/checkout@v4
      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli
      - name: "Test '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .
