name: "Test each dev container feature"
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  tests:
    name: "Test '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features:
          - perl
        baseImage:
          - debian:latest
          - ubuntu:latest
          - mcr.microsoft.com/devcontainers/base:debian
          - mcr.microsoft.com/devcontainers/base:ubuntu
          - mcr.microsoft.com/devcontainers/base:alpine
    steps:
      - uses: actions/checkout@v4
      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli
      - name: "Run tests"
        run: devcontainer features test --features ${{ matrix.features }} --base-image ${{ matrix.baseImage }}
